version: '2'
services:
    web:
        image: shivergard/docker-webserver
        ports:
            - 80:80
            - 86:86
        volumes:
            - .:/var/www
        links:
            - chatbot:chatbot
    chatbot:
        image: shivergard/chatbot
        volumes:
            - ./storage/php_requests:/chatbot-rnn/storage/php_request 
            - ./storage/models:/chatbot-rnn/models 
        ports:
            - 81:80
            - 21:22
    mysql:
        image: mariadb:latest
        env_file:
            - ./.mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql